# Generated by Django 5.2 on 2025-04-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRole', models.CharField(max_length=100, verbose_name='User Role')),
                ('userName', models.CharField(max_length=255, verbose_name='User Name')),
                ('emailId', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation')),
                ('mobileNumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
            ],
            options={
                'db_table': 'Usertable',
            },
        ),
    ]
