# Generated by Django 5.2 on 2025-04-29 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userRole', models.CharField(choices=[('candidate', 'Candidate'), ('sme', 'SME'), ('examiner', 'Examiner'), ('admin', 'Admin')], max_length=20, verbose_name='User Role')),
                ('userName', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='User Name')),
                ('employeeId', models.CharField(default='', max_length=100, verbose_name='Employee ID')),
                ('department', models.CharField(choices=[('tech', 'Tech'), ('quality_check', 'Quality Check'), ('media', 'Media'), ('business_development', 'Business Development')], max_length=100, verbose_name='Department')),
                ('designation', models.CharField(choices=[('developer', 'Developer'), ('qc_analysis', 'QC Analysis'), ('business_development_executive', 'Business Development Executive')], max_length=100, verbose_name='Designation')),
                ('emailId', models.EmailField(max_length=254, unique=True, verbose_name='Email ID')),
                ('mobileNumber', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('isAccountLocked', models.BooleanField(default=False, verbose_name='Is Account Locked')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='LoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_credentials', to='accounts.user')),
            ],
            options={
                'db_table': 'login_credentials',
            },
        ),
    ]
