# Generated by Django 5.2 on 2025-04-21 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adduser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userRole', models.CharField(choices=[('candidate', 'Candidate'), ('sme', 'SME'), ('examiner', 'Examiner'), ('admin', 'Admin')], max_length=20, verbose_name='User Role')),
                ('userName', models.CharField(max_length=255, verbose_name='User Name')),
                ('employeeId', models.CharField(default='', max_length=100, verbose_name='Employee ID')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('emailId', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobileNumber', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('activeRemarks', models.TextField(blank=True, verbose_name='Active Status Remarks')),
                ('isAccountLocked', models.BooleanField(default=False, verbose_name='Is Account Locked')),
                ('lockedRemarks', models.TextField(blank=True, verbose_name='Locked Status Remarks')),
                ('is_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AddUserTable',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
