# Generated by Django 5.2 on 2025-04-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adduser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userRole', models.CharField(choices=[('candidate', 'Candidate'), ('sme', 'SME'), ('examiner', 'Examiner'), ('admin', 'Admin')], max_length=20, verbose_name='User Role')),
                ('userName', models.CharField(max_length=255, verbose_name='User Name')),
                ('employeeId', models.CharField(default='', max_length=100, verbose_name='Employee ID')),
                ('department', models.CharField(choices=[('tech', 'Tech'), ('quality_check', 'Quality Check'), ('media', 'Media'), ('business_development', 'Business Development')], max_length=100, verbose_name='Department')),
                ('designation', models.CharField(choices=[('developer', 'Developer'), ('qc_analysis', 'QC Analysis'), ('business_development_executive', 'Business Development Executive')], max_length=100, verbose_name='Designation')),
                ('emailId', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobileNumber', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('isAccountLocked', models.BooleanField(default=False, verbose_name='Is Account Locked')),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='Adduser',
        ),
    ]
