# Generated by Django 5.2 on 2025-04-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_delete_adduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employeeId',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(max_length=10, verbose_name='Mobile Number'),
        ),
    ]
