# Generated by Django 5.2 on 2025-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_employeeid_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employeeId',
            field=models.CharField(default='', max_length=100, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobileNumber',
            field=models.CharField(max_length=20, verbose_name='Mobile Number'),
        ),
    ]
