# Generated by Django 5.2 on 2025-04-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_employeeid_alter_user_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
